# Generated by Django 4.1.1 on 2022-10-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="DEFAULT VALUE", max_length=500)),
                ("foto_perfil", models.FileField(upload_to="")),
                (
                    "pagina_web",
                    models.CharField(default="DEFAULT VALUE", max_length=1000),
                ),
                ("descripcion", models.TextField(default="DEFAULT VALUE")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
    ]
