# Generated by Django 4.1.1 on 2022-10-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entradas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="DEFAULT VALUE", max_length=5000)),
                ("contenido", models.TextField(default="DEFAULT VALUE")),
                ("imagen_destacada", models.FileField(upload_to="")),
                ("slug", models.CharField(default="DEFAULT VALUE", max_length=5000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "entradas",
            },
        ),
    ]
